import pandas as pd
import numpy as np

def calculate_rsi(series: pd.Series, period: int = 14) -> pd.Series:
    """Calculate Relative Strength Index (RSI)."""
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).copy()
    loss = (-delta.where(delta < 0, 0)).copy()
    
    # Use exponential moving average for smoothing
    avg_gain = gain.ewm(alpha=1/period, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1/period, adjust=False).mean()
    
    rs = avg_gain / avg_loss.replace(0, 1e-9)  # Avoid division by zero
    rsi = 100 - (100 / (1 + rs))
    return rsi

def calculate_macd(series: pd.Series, fast: int = 12, slow: int = 26, signal: int = 9) -> tuple:
    """Calculate MACD line, Signal line, and Histogram."""
    ema_fast = series.ewm(span=fast, adjust=False).mean()
    ema_slow = series.ewm(span=slow, adjust=False).mean()
    macd_line = ema_fast - ema_slow
    signal_line = macd_line.ewm(span=signal, adjust=False).mean()
    macd_hist = macd_line - signal_line
    return macd_line, signal_line, macd_hist

def calculate_bollinger_bands(series: pd.Series, period: int = 20, num_std: float = 2.0) -> tuple:
    """Calculate Upper, Middle (SMA), and Lower Bollinger Bands."""
    sma = series.rolling(window=period).mean()
    std = series.rolling(window=period).std()
    upper_band = sma + (std * num_std)
    lower_band = sma - (std * num_std)
    return upper_band, sma, lower_band

def generate_technical_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generate technical indicators from a DataFrame containing Close and Volume.
    Modifies DataFrame in-place or returns a copy with features.
    """
    df = df.copy()
    
    # Price close series
    close = df["close"]
    
    # 1. Moving Averages
    df["ema_9"] = close.ewm(span=9, adjust=False).mean()
    df["ema_21"] = close.ewm(span=21, adjust=False).mean()
    df["sma_50"] = close.rolling(window=50).mean()
    
    # 2. RSI
    df["rsi_14"] = calculate_rsi(close, 14)
    
    # 3. MACD
    macd_l, signal_l, hist_l = calculate_macd(close)
    df["macd_line"] = macd_l
    df["macd_signal"] = signal_l
    df["macd_hist"] = hist_l
    
    # 4. Bollinger Bands
    upper, middle, lower = calculate_bollinger_bands(close)
    df["bb_upper"] = upper
    df["bb_middle"] = middle
    df["bb_lower"] = lower
    
    # 5. Price & Volume Changes
    df["price_change_5d"] = close.pct_change(5, fill_method=None)
    df["volume_change_5d"] = df["volume"].pct_change(5, fill_method=None)
    
    # 6. Normalized position indicators (e.g. distance from SMA 50)
    df["dist_sma_50"] = (close - df["sma_50"]) / df["sma_50"].replace(0, 1e-9)
    df["bb_width"] = (df["bb_upper"] - df["bb_lower"]) / df["bb_middle"].replace(0, 1e-9)
    
    # Fill NaN and inf values generated by rolling windows or division by zero
    df = df.replace([np.inf, -np.inf], np.nan)
    df = df.bfill().ffill().fillna(0.0)
    
    return df
